[package]
name = "rustgenpass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
lazy_static = "1.4.0"
md-5 = "0.10.4"
#md5 = "0.7.0"
regex = "1.6.0"
